apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-o14y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-emic-tenant/rhtap-demo-app/hacbs-test-project-o14y@sha256:5824874c7dec19f23056574de4fc9eea711f9136986277d2f248ff953fdb209c
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
