apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-o14y
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-emic-tenant/rhtap-demo-app/hacbs-test-project-o14y@sha256:e2468662286a65c45f0af3205d9f297d06bb8a9256f821e7ae6ed36048e331e8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
