apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-o14y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-o14y
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-o14y
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-o14y
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-o14y
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-emic-tenant/rhtap-demo-app/hacbs-test-project-o14y@sha256:5824874c7dec19f23056574de4fc9eea711f9136986277d2f248ff953fdb209c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
